"""empty message

Revision ID: 2bc0514ee4a8
Revises: d2ae914e2ab4
Create Date: 2025-06-22 11:13:18.413750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc0514ee4a8'
down_revision: Union[str, None] = 'd2ae914e2ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('title')
    )
    op.drop_table('organization')
    op.alter_column('activities', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('organization',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('building_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('organization_activity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('organization_building_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_pkey')),
    sa.UniqueConstraint('phone', name=op.f('organization_phone_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('title', name=op.f('organization_title_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('organizations')
    # ### end Alembic commands ###
