"""empty message

Revision ID: 5168e085b862
Revises: 479b7a1810bd
Create Date: 2025-06-23 08:54:31.522626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5168e085b862'
down_revision: Union[str, None] = '479b7a1810bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('buildings', sa.Column('longitude', sa.Float(), nullable=False))
    op.drop_constraint(op.f('buildings_coordinates_key'), 'buildings', type_='unique')
    op.drop_column('buildings', 'coordinates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('coordinates', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('buildings_coordinates_key'), 'buildings', ['coordinates'], postgresql_nulls_not_distinct=False)
    op.drop_column('buildings', 'longitude')
    op.drop_column('buildings', 'latitude')
    # ### end Alembic commands ###
